apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infrastructure
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 12.0.7
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: https://github.com/Laudenlaruto/improved-octo-doodle.git
      targetRevision: HEAD
      path: apps/traefik/
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
